In [3]:
import torch
print(torch.__version__)

2.6.0+cu124


In [4]:
if torch.cuda.is_available():
  print("GPU ")
  print("Devide : ",torch.cuda.get_device_name())
else:
  print("No GPU")

No GPU


# **Creating tensors**

In [4]:
# Torch empty
a= torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
a.dtype

torch.float32

In [7]:

# Torch zeros
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
# Torch Ones

torch.ones(4,3,dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# rand with generator seed
gen=torch.Generator()
gen.manual_seed(42)
torch.rand(2,3,generator=gen)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [10]:
# rand with manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2],[2,3]])

tensor([[1, 2],
        [2, 3]])

In [12]:
# other ways
print(" using arange -> ",torch.arange(1,10,3))

print("Using linspace -> ",torch.linspace(1,10,7,dtype=torch.float32))

print("Identity matrix -> ")
print(torch.eye(5))

print("Full matrix of same value -> ")
print(torch.full((3,3),5.1,dtype=torch.int32))

 using arange ->  tensor([1, 4, 7])
Using linspace ->  tensor([ 1.0000,  2.5000,  4.0000,  5.5000,  7.0000,  8.5000, 10.0000])
Identity matrix -> 
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Full matrix of same value -> 
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]], dtype=torch.int32)


# **Tensor Shape**


In [13]:
# Tensor Shape
a=torch.tensor([[1,2,3],[4,5,6]])

In [14]:
a.shape

torch.Size([2, 3])

In [15]:
# empty like a method to create similar dimension empty array
torch.empty_like(a)

tensor([[                  0, 7235419174270214779, 7005410123583601186],
        [3702915663014147638, 7218486479376624993, 3978705116472751671]])

In [25]:
torch.rand_like(a,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# **Torch Datatype**

In [16]:
# find datatype
a.dtype

torch.int64

In [18]:
# assign datatype
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [20]:
x=torch.tensor([1,2,3],dtype=torch.float32)

In [22]:
x.to(dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

# **Mathematical Operation**

1. Scaler Operation

In [27]:
x=torch.rand((2,3))
x

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [28]:
x+2

tensor([[2.2239, 2.3023, 2.1784],
        [2.8238, 2.5557, 2.9770]])

In [29]:
x-1

tensor([[-0.7761, -0.6977, -0.8216],
        [-0.1762, -0.4443, -0.0230]])

In [30]:
x*3

tensor([[0.6717, 0.9070, 0.5353],
        [2.4715, 1.6672, 2.9311]])

In [32]:
x*100//50

tensor([[0., 0., 0.],
        [1., 1., 1.]])

In [33]:
x**2

tensor([[0.0501, 0.0914, 0.0318],
        [0.6787, 0.3089, 0.9546]])

In [37]:
# performing operator between two tensors
a=torch.rand((2,3))
b=torch.rand((2,3))
print(a)
print(b)

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])
tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])


In [38]:
a+b

tensor([[1.5262, 1.1519, 1.1346],
        [1.0966, 1.3615, 1.1744]])

In [39]:
a-b

tensor([[ 0.2839,  0.0458, -0.2446],
        [ 0.3591, -0.4490, -0.4967]])

In [40]:
a*b

tensor([[0.5622, 0.3312, 0.3069],
        [0.2684, 0.4130, 0.2831]])

In [41]:
a/b

tensor([[1.4571, 1.0829, 0.6453],
        [1.9738, 0.5040, 0.4055]])

In [46]:
# abs
a=torch.tensor([1.35534,-2,3,4])

In [47]:
torch.abs(a)

tensor([1.3553, 2.0000, 3.0000, 4.0000])

In [48]:
# neg
torch.neg(a)

tensor([-1.3553,  2.0000, -3.0000, -4.0000])

In [49]:
# round
torch.round(a)

tensor([ 1., -2.,  3.,  4.])

In [50]:
# ceil
torch.ceil(a)

tensor([ 2., -2.,  3.,  4.])

In [51]:
torch.floor(a)

tensor([ 1., -2.,  3.,  4.])

In [52]:
torch.clamp(a,min=2,max=3)

tensor([2., 2., 3., 3.])

# 3.Reduction

In [61]:
a=torch.randint(size=(2,3),low=1,high=10,dtype=torch.float32)
a

tensor([[3., 6., 3.],
        [9., 4., 6.]])

In [57]:
# sum
torch.sum(a)

tensor(16)

In [58]:
torch.sum(a,dim=0)

tensor([3, 8, 5])

In [59]:
torch.sum(a,dim=1)

tensor([ 3, 13])

In [64]:
torch.mean(a)

torch.mean(a,axis=0)

torch.median(a,axis=1)

torch.return_types.median(
values=tensor([3., 6.]),
indices=tensor([2, 2]))

# **torch array multiplication**

In [4]:
x=torch.arange(6).reshape(2,3)

In [5]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [14]:
x=torch.tensor([1,2,3])
y=torch.tensor([1,4,5])

In [15]:
torch.dot(x,y)

tensor(24)

In [19]:
y.reshape(-1,6)

tensor([[0, 1, 2, 3, 4, 5]])

# Broadcasting

In [22]:
a = torch.arange(1,4)

In [23]:
print(a)

tensor([1, 2, 3])


In [30]:
a=a.reshape((3,1))

In [33]:
x=torch.tensor([1,2,3])

In [34]:
x+a

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [35]:
x>a

tensor([[False,  True,  True],
        [False, False,  True],
        [False, False, False]])

In [38]:
a=torch.ones((2, 3, 1))

In [39]:
print(a)

tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])


In [41]:
b=torch.ones((3,))

In [42]:
b

tensor([1., 1., 1.])

# **Fully connected layer**

In [5]:
x=torch.arange(50).view(10,5)

In [6]:
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]])

In [7]:
layer=torch.nn.Linear(in_features=5,out_features=3)

In [12]:
layer.weight

Parameter containing:
tensor([[-0.1154,  0.3783,  0.4367, -0.2308,  0.1475],
        [ 0.1088, -0.3279, -0.0135, -0.3113,  0.1556],
        [-0.1219, -0.0399, -0.1319,  0.3255,  0.4029]], requires_grad=True)

In [13]:
layer.bias

Parameter containing:
tensor([-0.0995, -0.1743,  0.0067], requires_grad=True)